# Original QR factorization

In [1]:
import numpy as np

In [2]:
A = np.random.random((5,3))

In [3]:
q, r = np.linalg.qr(A)

In [4]:
q

array([[-0.78334735,  0.43098466,  0.05420773],
       [-0.11436008, -0.68269327,  0.1249882 ],
       [-0.10138237,  0.0486264 , -0.92736328],
       [-0.01353576, -0.40109645, -0.34147035],
       [-0.60235131, -0.43004563,  0.06953285]])

In [5]:
r

array([[-1.24466698, -0.63568048, -0.55188147],
       [ 0.        , -0.63489161, -0.43138699],
       [ 0.        ,  0.        , -0.5533442 ]])

In [6]:
q, r = np.linalg.qr(A, mode='complete')

In [7]:
q

array([[-0.78334735,  0.43098466,  0.05420773,  0.14677336, -0.41968828],
       [-0.11436008, -0.68269327,  0.1249882 , -0.37624244, -0.60305162],
       [-0.10138237,  0.0486264 , -0.92736328, -0.35682661, -0.00540414],
       [-0.01353576, -0.40109645, -0.34147035,  0.83872132, -0.13741532],
       [-0.60235131, -0.43004563,  0.06953285, -0.07823377,  0.66428783]])

In [8]:
r

array([[-1.24466698, -0.63568048, -0.55188147],
       [ 0.        , -0.63489161, -0.43138699],
       [ 0.        ,  0.        , -0.5533442 ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])

# Gram-Schmidt Column Pivoting

In [9]:
def qr_pivoting(A):
    
    n, m = A.shape
    q = np.zeros((n, m))
    r = np.zeros((m, m))
    
    for j in range(m):
        i = np.argmax(np.linalg.norm(A, 2, axis=0))
        qj = A[:, i] / np.linalg.norm(A[:, i], 2)
        q[:, j] = qj
        rj = qj.T @ A
        r[j, :] = rj
        A = A - qj[:, np.newaxis] @ rj[np.newaxis, :]
    
    return q, r

In [10]:
q, r = qr_pivoting(A)

In [11]:
q

array([[ 0.78334735, -0.30773589, -0.30656953],
       [ 0.11436008,  0.32117145,  0.61525689],
       [ 0.10138237,  0.70147279, -0.60852536],
       [ 0.01353576,  0.51591077,  0.10637876],
       [ 0.60235131,  0.20956987,  0.38190906]])

In [12]:
r

array([[1.24466698e+00, 6.35680481e-01, 5.51881473e-01],
       [0.00000000e+00, 3.90353912e-01, 7.01629915e-01],
       [0.00000000e+00, 5.00710672e-01, 1.44142213e-17]])

In [13]:
A

array([[0.97500658, 0.22433008, 0.21639818],
       [0.14234022, 0.5061327 , 0.28845671],
       [0.12618728, 0.0335743 , 0.54812534],
       [0.01684752, 0.26325719, 0.36944856],
       [0.74972678, 0.65593533, 0.47946702]])

In [14]:
q.T @ q

array([[ 1.00000000e+00, -4.83733358e-17, -1.08145074e-16],
       [-4.83733358e-17,  1.00000000e+00, -9.41471666e-17],
       [-1.08145074e-16, -9.41471666e-17,  1.00000000e+00]])