# QR Factorization using Householder's Reflection

In [1]:
import numpy as np

In [2]:
A = np.random.rand(100, 100)

In [3]:
A

array([[0.72798224, 0.51885804, 0.94811842, ..., 0.99839576, 0.1868386 ,
        0.75734292],
       [0.31695615, 0.72312502, 0.37719169, ..., 0.46483308, 0.73714098,
        0.3899721 ],
       [0.68805059, 0.94377712, 0.65182093, ..., 0.04899381, 0.31859145,
        0.12378684],
       ...,
       [0.219637  , 0.64890156, 0.31687846, ..., 0.33828024, 0.48662042,
        0.67259646],
       [0.56682626, 0.68616931, 0.01613934, ..., 0.41188597, 0.22295755,
        0.05977781],
       [0.11361736, 0.86367671, 0.9653844 , ..., 0.49225671, 0.3641489 ,
        0.5132201 ]])

In [4]:
def householder(A: np.ndarray):
    """QR factorization using Householder's reflection for square matrices"""
    
    n = A.shape[0]
    QT = np.identity(n)
    R = np.zeros((n, n))
    
    for k in range(n-1):
        H = np.identity(n)
        
        
        a_lower = A[k:, k]
        a_lower_norm = np.linalg.norm(a_lower)
        
        R[:k, k] = A[:k ,k]
        R[k ,k] = a_lower_norm
        
        r_lower = np.zeros_like(a_lower)
        r_lower[0] = a_lower_norm
        
        v = a_lower - r_lower
        v = v / np.linalg.norm(v)  # Normalize v
        
        H_lower = np.identity(n - k) - 2 * v[:, np.newaxis] @ v[np.newaxis, :] # H = I - 2 v @ v.T
        

        H[k:, k:] = H_lower
        A = H @ A
        QT = H @ QT
    
    R[:, -1] = A[:, -1]
    return QT.T, R

In [5]:
%%time
q, r = householder(A)

Wall time: 49.4 ms


In [6]:
q

array([[ 0.13879368, -0.04996001,  0.13991244, ...,  0.10688638,
        -0.01499256, -0.13630815],
       [ 0.06042937,  0.11466522, -0.02095144, ..., -0.15129406,
         0.04290769,  0.08822906],
       [ 0.1311805 ,  0.07716986, -0.00925654, ..., -0.08955497,
         0.117923  , -0.05363377],
       ...,
       [ 0.04187496,  0.12001045, -0.01800007, ...,  0.00888476,
        -0.22050112, -0.00339839],
       [ 0.10806844,  0.03851682, -0.15901512, ...,  0.01554659,
        -0.07228845,  0.12282015],
       [ 0.02166175,  0.20694388,  0.16860517, ..., -0.13551087,
         0.0603657 , -0.0493545 ]])

In [7]:
r

array([[ 5.24506747,  5.05033309,  4.22732265, ...,  4.43530189,
         4.30472334,  4.13520484],
       [ 0.        ,  3.6448414 ,  1.64068191, ...,  1.70429858,
         1.88244175,  1.90444288],
       [ 0.        ,  0.        ,  3.1688476 , ...,  1.49236697,
         0.57709206,  1.12913269],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.62364113,
         0.04181049,  0.27673447],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.16972205, -0.01493076],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.00590068]])

# Original QR using NumPy

In [8]:
%%time
q, r = np.linalg.qr(A)

Wall time: 33.8 ms


In [9]:
q

array([[-0.13879368,  0.04996001,  0.13991244, ..., -0.10688638,
        -0.01499256,  0.13630815],
       [-0.06042937, -0.11466522, -0.02095144, ...,  0.15129406,
         0.04290769, -0.08822906],
       [-0.1311805 , -0.07716986, -0.00925654, ...,  0.08955497,
         0.117923  ,  0.05363377],
       ...,
       [-0.04187496, -0.12001045, -0.01800007, ..., -0.00888476,
        -0.22050112,  0.00339839],
       [-0.10806844, -0.03851682, -0.15901512, ..., -0.01554659,
        -0.07228845, -0.12282015],
       [-0.02166175, -0.20694388,  0.16860517, ...,  0.13551087,
         0.0603657 ,  0.0493545 ]])

In [10]:
r

array([[-5.24506747, -5.05033309, -4.22732265, ..., -4.43530189,
        -4.30472334, -4.13520484],
       [ 0.        , -3.6448414 , -1.64068191, ..., -1.70429858,
        -1.88244175, -1.90444288],
       [ 0.        ,  0.        ,  3.1688476 , ...,  1.49236697,
         0.57709206,  1.12913269],
       ...,
       [ 0.        ,  0.        ,  0.        , ..., -0.62364113,
        -0.04181049, -0.27673447],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.16972205, -0.01493076],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , -0.00590068]])